### ISSUE TITLE
suggestion: time format change

### ISSUE THREAD

**Issue by peterzhou99** [Labii/Labii-ELN-LIMS#3]
I did a trial on Labii online applicaiton and suggest that it is better to change time format from "3 minutes ago" to "2017.05.15 12:30:48 +08:00", which is a fixed time display. Hope it is more convenient for display and print.

**Comment by weasteam** [comment]
Hi Zhou,

Our design principle is simple and readable. We have specifically chosen such format because it is human readable and easy to be displayed on a mobile device. The time format used in Labii follows this rule:

1) If the `datetime` was made within 24 hours. It will be displayed as `xx hours, xx minutes ago`
2) If the `datetime` was made beyond 24 hours. It will be displayed as `M d, Y` (`Y` will be hidden if it is same to current year). For example `May 14th, 2016`

At this moment, we do not have a plan to format the `datetime` to `2017.05.15 12:30:48 +08:00` in this two reasons:
1) It is not very easy for human to read
2) It took too much space (especially in a cell of a table)
3) When the time needs to be displayed as fixed, it is actually displayed in the format as you described. For example, the time in signature is displayed as `2017-04-05 20:05:01+00:00`

Let me know if you have any other question.

**Comment by peterzhou99** [comment]
Thanks for your quick and detailed reply, 
Your current design is better for online display both PC and mobile. But if we print out the report and read it offline, the time is still displayed "3 minutes ago", which seems not likely GxP regulated.  It is hard for reader to calculate exact time with "3 minutes ago".

**Comment by weasteam** [comment]
I see.

Thank you for reporting this. What you described totally make sense. I will add the feature request to our development to-do list.

**Comment by weasteam** [comment]
We have fixed the issue. The `datetime` was updated to `2017.05.15 12:30:48 +08:00` at the print view.
